Use the following code for the questions below:


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

How many negative numbers are there?

How many positive numbers are there?

How many even positive numbers are there?

If you were to add 3 to each data point, how many positive numbers would there be?

If you squared each number, what would the new mean and standard deviation be?

A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

Calculate the z-score for each data point. Recall that the z-score is given by:

Z =  (x-μ)/σ
Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [31]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
print(f"{np.count_nonzero(a < 0)} negative numbers")
print(f"{np.count_nonzero(a > 0)} positive numbers")
print(f"{np.count_nonzero(a % 2 != 0)} even numbers")
print(f"{np.count_nonzero((a+3) % 2 != 0)} even numbers")
print(f"{((a*a).mean())} mean of data squared")
print(f"{((a*a).std())} stdev of data squared")
print(f"{a - a.mean()} centered dataset")
print(f"{(a - a.mean())/(a.std())} z scores")


4 negative numbers
5 positive numbers
4 even numbers
8 even numbers
74.0 mean of data squared
144.0243035046516 stdev of data squared
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.] centered dataset
[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735] z scores


In [76]:
## Setup 1
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold 
# the sum of all the numbers in above list
sum_of_a = 0
sum_of_a = sum(a)
print(f'{sum_of_a} sum of a')

# Exercise 2 - Make a variable named min_of_a to hold 
# the minimum of all the numbers in the above list
min_of_a = 0
min_of_a = min(a)
print(f'{min_of_a} min of a')

# Exercise 3 - Make a variable named max_of_a to hold 
# the max number of all the numbers in the above list
max_of_a = 0
max_of_a = max(a)
print(f'{max_of_a} max of a')

# Exercise 4 - Make a variable named mean_of_a to hold 
# the average of all the numbers in the above list
mean_of_a = 0
mean_of_a = sum_of_a/len(a)
print(f'{mean_of_a} mean of a')

# Exercise 5 - Make a variable named product_of_a to hold 
# the product of multiplying all the numbers in the above list together
product_of_a = 1
for x in a:
    product_of_a = product_of_a * x
print(f'{product_of_a} product of a')

# Exercise 6 - Make a variable named squares_of_a. 
# It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = []
for x in a:
    squares_of_a.append(x*x)
print(f'{squares_of_a} squares of a')

# Exercise 7 - Make a variable named odds_in_a. 
# It should hold only the odd numbers
odds_in_a = []
for x in a:
    if x % 2 == 1:
        odds_in_a.append((x))
print(f'{odds_in_a} odds of a')

# Exercise 8 - Make a variable named evens_in_a. 
# It should hold only the evens.
evens_in_a = []
for x in a:
    if x % 2 == 0:
        evens_in_a.append((x))
print(f'{evens_in_a} evens of a')


55 sum of a
1 min of a
10 max of a
5.5 mean of a
3628800 product of a
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100] squares of a
[1, 3, 5, 7, 9] odds of a
[2, 4, 6, 8, 10] evens of a


In [131]:
import numpy as np
## What about life in two dimensions? A list of lists is matrix, 
# a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, 
# average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b=np.array(b)

# Exercise 1 - refactor the following to use numpy. 
# Use sum_of_b as the variable. **Hint, you'll first need to 
# make sure that the "b" variable is a numpy array**
sum_of_b = 0
sum2_of_b = 0
for row in b:
    sum_of_b += sum(row)
print(sum_of_b)

sum2_of_b = b.sum()
print(sum2_of_b)

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 
print(min_of_b)

print(b.min())

# Exercise 3 - refactor the following maximum calculation to 
# find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
print(max_of_b)

print(b.max())

# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
print(mean_of_b)

print(np.mean(b))

# Exercise 5 - refactor the following to use numpy for 
# calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
print(product_of_b)

print(np.product(b))

# Exercise 6 - refactor the following to use numpy to find 
# the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
print(squares_of_b)

b2 = (b*b)
print(b2.flatten(order = 'C'))

# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
print(odds_in_b)

print((b[b % 2 == 1]))

# Exercise 8 - refactor the following to use numpy to filter 
# only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
print(evens_in_b)

print((b[b % 2 == 0]))

# Exercise 9 - print out the shape of the array b.
print(b.shape)
# Exercise 10 - transpose the array b.
print(np.transpose(b))
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
print(b.flatten(order = "C"))
# Exercise 12 - reshape the array b to be a list of 6 lists, 
# each containing only 1 number (6 x 1)
print(b.flatten(order = "F"))

33
33
3
3
8
8
5.5
5.5
20160
20160
[9, 16, 25, 36, 49, 64]
[ 9 16 25 36 49 64]
[3, 5, 7]
[3 5 7]
[4, 6, 8]
[4 6 8]
(2, 3)
[[3 6]
 [4 7]
 [5 8]]
[3 4 5 6 7 8]
[3 6 4 7 5 8]


In [195]:
## Setup 3
import numpy as np
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c=np.array(c)

# HINT, you'll first need to make sure that the "c" variable 
# is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
print(c.min(),c.max(),c.sum(),np.product(c))
# Exercise 2 - Determine the standard deviation of c.
print(c.std())
# Exercise 3 - Determine the variance of c.
print(np.var(c))
# Exercise 4 - Print out the shape of the array c
print(c.shape)
# Exercise 5 - Transpose c and print out transposed result.
print(np.transpose(c), "c transposed")
# Exercise 6 - Get the dot product of the array c with c. 
print(np.dot(c,c),"dot product")
# Exercise 7 - Write the code necessary to sum up the result of 
# c times c transposed. Answer should be 261
print((np.multiply(c,np.transpose(c))).sum(),"sum of c*c-transposed")
# Exercise 8 - Write the code necessary to determine the product of 
# c times c transposed. Answer should be 131681894400.
print(np.product(np.multiply(c,np.transpose(c)).flatten(order="C")))

1 9 45 362880
2.581988897471611
6.666666666666667
(3, 3)
[[1 4 7]
 [2 5 8]
 [3 6 9]] c transposed
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]] dot product
261 sum of c*c-transposed
131681894400


In [196]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)
#print(d)
# Exercise 1 - Find the sine of all the numbers in d
print(np.sin(d))
# Exercise 2 - Find the cosine of all the numbers in d
print(np.cos(d))
# Exercise 3 - Find the tangent of all the numbers in d
print(np.tan(d))
# Exercise 4 - Find all the negative numbers in d
print(d[d < 0])
# Exercise 5 - Find all the positive numbers in d
print(d[d > 0])
# Exercise 6 - Return an array of only the unique numbers in d.
print(np.unique(d))
# Exercise 7 - Determine how many unique numbers there are in d.
print(np.unique(d).size)
# Exercise 8 - Print out the shape of d.
print(d.shape)
# Exercise 9 - Transpose and then print out the shape of d.
print(np.transpose(d))
# Exercise 10 - Reshape d into an array of 9 x 2
print(np.array(d).reshape((9,2)))


[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]
[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]
[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]
[-90 -30 -45 -45]
[ 90  30  45 120 180  45 270  90  60  45  90 180]
[-90 -45 -30   0  30  45  60  90 120 180 270]
11
(3, 6)
[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]
[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]]
